### ISSUE TITLE
Show error Message when token is invalid

### ISSUE THREAD

**Issue by ModProg** [Xithrius/terminal-twitch-chat#26]
I set it up using a token I already had, but it seam to have had insufficent permissions which let to a hard to diagnose silent error.

**Comment by Xithrius** [comment]
Hello!

From what I can tell in your config, I'd suggest not modifying `maximum_username_length` as it's used for centering. If a username is longer than 12 then some bugs will occur. I'll be fixing this in the near future, so keep it at Twitch's maximum username length of 26 for now.

You may not be on the correct version of the binary, so try `cargo install terminal-twitch-chat` to update.

This might be at fault of Twitch's connectivity with IRCs, so simply turning the program off and on again may do the trick.

If that doesn't work, what OS are you on, and where did you place this config file?

**Comment by ModProg** [comment]
![image](https://user-images.githubusercontent.com/11978847/134055934-dee0232b-f638-4072-9604-56ba2ec55224.png)
It is running fine, but messages are neither send nor recieved

**Comment by ModProg** [comment]
I'm running on the latest stable rust on arch linux.

**Comment by Xithrius** [comment]
Interesting, since I'm also running that same OS, I'm guessing it's something to do with the config file. Where did you place it?

**Comment by ModProg** [comment]
`~/.config/ttc/config.toml`

**Comment by Xithrius** [comment]
And you've done `cargo install terminal-twitch-chat` once again just to be sure you're in the latest version?

**Comment by ModProg** [comment]
yes I even ran it with --force to force a reinstall

**Comment by Xithrius** [comment]
You're supposed to get the token from https://twitchapps.com/tmi/, which can be found in the Twitch IRC docs, in the `Connecting to Twitch IRC` section: https://dev.twitch.tv/docs/irc/guide/

> To quickly get a token for your account, use this [Twitch Chat OAuth Password Generator](https://dev.twitch.tv/docs/irc/guide/).

**Comment by ModProg** [comment]
Alright thanks, that works. We could make this issue into an "show error on insufficient token".

**Comment by Xithrius** [comment]
The IRC connects no matter what, as far as I know. I can check if this is correct.

**Comment by Xithrius** [comment]
Oh wait I see what I've been doing wrong, there's a ton of `.unwrap()` method calls in [`src/twitch.rs`](https://github.com/Xithrius/terminal-twitch-chat/blob/main/src/twitch.rs#L25-L27).

**Comment by Xithrius** [comment]
I'll fix this up once I make sure that `.pre-commit-config.yaml` is working properly.

**Comment by Xithrius** [comment]
I've started to work on this, hopefully I can find a fix with the `irc` crate.

**Comment by Xithrius** [comment]
The unwraps that I placed actually do nothing in terms of error handling incorrect tokens, so I'm going to have to dig a bit deeper into how the problem should be avoided.

If I can't find any coherent solution in the `irc` crate, I'll probably use regex to filter out tokens that don't have `oauth:` at the start, followed by a certain amount (or range) of characters.

**Comment by ModProg** [comment]
makes sense, strange that the irc crate doesn't throw an error

**Comment by Xithrius** [comment]
Thank you @ModProg for finding this bug. Fixes have been included in [v1.1.1](https://github.com/Xithrius/terminal-twitch-chat/releases/tag/v1.1.1).
